swagger: "2.0"

info:
  version: 0.1a
  title: improvementTrackerAPI
  description: Demonstrator API for Improvement Tracker SaaS

paths:
# -----------------------------------
# Improvements
# -----------------------------------
  /improvements:
    get:
      summary: Get list of improvements
      operationId: improvements.getImprovements
      responses:
        200:
          description: Successful get
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                description:
                  type: string
                benefits:
                  type: array
                  items:
                    $ref: '#/definitions/BenefitType'
# -----------------------------------
# Alerts
# -----------------------------------
  /improvements/alerts:
    get:
      summary: Get the alert messages
      description: Get the alert messages for the current user
      operationId: improvements.getAlerts
      responses:
        200:
          description: JSON array of alerts to display
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                message:
                  type: string
    post:
      summary: Dismiss an alert message
      operationId: improvements.dismissAlert
      parameters:
        - name: DismissAlertContent
          in: body
          schema:
            type: object
            properties:
              alertNum:
                type: integer
          required: true
      responses:
        200:
          description: OK
# -----------------------------------
# Objectives
# -----------------------------------
  /improvements/objectives:
    get:
      summary: Get list of objectives
      operationId: improvements.getObjectives
      responses:
        200:
          description: JSON array of objectives to display
          schema:
            type: array
            # Benefits and Objectives use the same schema
            items:
              $ref: '#/definitions/BenefitType'
    post:
      summary: Add new objective
      operationId: improvements.addObjective
      parameters:
        - name: NewObjective
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
          required: true
      responses: 
        200:
          description: OK
# -----------------------------------
# Benefits
# -----------------------------------
  /improvements/benefits:
    get:
      summary: Get list of benefit categories
      operationId: improvements.getBenefits
      responses:
        200:
          description: JSON array of benefits to display
          schema:
            type: array
            items:
              $ref: '#/definitions/BenefitType'
# -----------------------------------
# Type Definitions
# -----------------------------------
definitions:
  BenefitType:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      id:
        type: integer
